name: robo3t
version: 1.2.1
summary: Robo 3T
description: Native and cross-platform MongoDB manager
confinement: strict
grade: stable

apps:
    robo3t:
        command: env LC_ALL=C QT_XKB_CONFIG_ROOT="$SNAP/usr/share/X11/xkb" QT_XCB_CONFIG_ROOT="$SNAP/usr/share/X11/xcb" desktop-launch robo3t
        plugs: [home, network, network-bind, unity7]

parts:
    tarball:
        plugin: dump
        source: https://download.robomongo.org/1.2.1/linux/robo3t-1.2.1-linux-x86_64-3e50a65.tar.gz
        after: [desktop-qt5]
        install: |
            rm $SNAPCRAFT_PART_INSTALL/lib/libstdc++*
